"""empty message

Revision ID: 822b1d790793
Revises: 5dc05a895a8c
Create Date: 2019-02-26 07:37:56.348314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822b1d790793'
down_revision = '5dc05a895a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET admin=False')
    op.alter_column('users', 'admin', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
