FROM python:3.7.2-slim

RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get -y install gcc && \
    apt-get -y install libpq-dev && \
    apt-get clean

WORKDIR /usr/src/app

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./entrypoint.sh .
RUN chmod +x ./entrypoint.sh

COPY . .

CMD ["/usr/src/app/entrypoint.sh"]